// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: esp32-5.0

#include "ui.h"

void ui_comp_Button2_create_hook(lv_obj_t * comp)
{
}
